### ISSUE TITLE
Modify Fl.bi to run under DOS

### ISSUE THREAD

**Issue by demosthenesk** [angros47/FLTK-headers-for-FreeBasic#2]
#ifdef FLTK_HAVE_CAIRO
#include once "Fl_Cairo.bi"
#endif

#include once "Enumerations.bi"

#ifdef __FB_DOS__
	#inclib "NX11"
	#inclib "freetype"
	#inclib "nano-X"
	#inclib "mwin"
	#inclib "stdcxx"
	#inclib "fltk"
#else
'FLTK is written in C++, so we need to include C++ runtime as well
#inclib "stdc++"

#inclib "fltk"

#ifndef __FB_WIN32__
	#inclib "X11"
	#inclib "Xrender"
	#inclib "Xext"
#endif
#endif

**Comment by angros47** [comment]
Done
